# Generated by Django 2.2.1 on 2019-05-25 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='内容对应的mongoid')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
